"""currency_combine

Revision ID: 916a75cd2288
Revises: c031f0fae632
Create Date: 2023-11-09 20:05:03.912630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '916a75cd2288'
down_revision: Union[str, None] = 'c031f0fae632'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptosamples', sa.Column('value_btc', sa.Float(), nullable=False))
    op.add_column('cryptosamples', sa.Column('value_eth', sa.Float(), nullable=False))
    op.drop_column('cryptosamples', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptosamples', sa.Column('value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('cryptosamples', 'value_eth')
    op.drop_column('cryptosamples', 'value_btc')
    # ### end Alembic commands ###
