"""init_rev

Revision ID: d8908ec887d2
Revises: 
Create Date: 2023-11-06 01:09:59.671303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = 'd8908ec887d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cryptosamples',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('symbol', sa.String(), nullable=True),
                    sa.Column('interval', sa.Integer(), nullable=True),
                    sa.Column('samples', sa.Integer(), nullable=True),
                    sa.Column('time_', sa.Integer(), nullable=True),
                    sa.Column('value', sa.Double(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cryptosamples')
    # ### end Alembic commands ###
