"""del_symbol

Revision ID: f71a34c0d122
Revises: 916a75cd2288
Create Date: 2023-11-09 20:10:16.081481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f71a34c0d122'
down_revision: Union[str, None] = '916a75cd2288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cryptosamples', 'symbol')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cryptosamples', sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
